language: node_js
node_js:
- '5'
compiler: clang-3.6
env:
  matrix:
  - CXX=clang-3.6
  global:
  - secure: ZC7U9902Jw4QQD1FlSq3hGIqtJq0OxOi7ReP7s/i2cxXlhMktksVkne/9wM60oQUrGlesbiXS5atlZFhwEml7dTgxpEs3bo7T/AWDxMkxynFuwLp2SOjRGqvMghCh7ZASTDKjbVR9f2slny/4rpyiu9KulwxEJ4uh4sqj74Nh4o=
  - secure: Tp1bJShbt5pS7WlYe6sM0A/HXkRKGyJJfllSV61C4Bwgro7It32gKQnnXPNpNUt1P6oYZ575CVqAtPvD7chxWkjaKo0PW5zmjW92nJ9Hn3tpP5zLC0CQ4KrMXR3dYS38xMn6FQoL8eXRpPD5+FxupUS7BuQmwqYVvtW79S4k60o=
sudo: false
addons:
  apt:
    sources:
    - llvm-toolchain-precise-3.6
    - ubuntu-toolchain-r-test
    packages:
    - clang-3.6
    - g++-4.8
cache:
- apt
- directories:
  - node_modules
after_success:
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_rsa
- ssh-add .travis/travis_rsa
- git config --global push.default simple
- git remote add test "${TEST_LOCATION}"
- git remote add deploy "${DEPLOY_LOCATION}"
- if [ "$TRAVIS_PULL_REQUEST" == "true" ]; then git push test master /dev/null 2>&1; else git push deploy master /dev/null 2>&1; fi
before_install:
- openssl aes-256-cbc -K $encrypted_d7ef8710d4fd_key -iv $encrypted_d7ef8710d4fd_iv
  -in .travis/secrets.tar.enc -out .travis/secrets.tar -d
- tar xvf .travis/secrets.tar -C .travis/
- mkdir -p ~/.ssh
- cp .travis/known_hosts ~/.ssh/known_hosts
- chmod 600 ~/.ssh/known_hosts
