name: ansible-test

on:
  # pull_request:
  #   types:[ opened, synchronize ]
    
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps: 
      - uses: actions/checkout@v3
      
      # Rebuild Mumbot image
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false # Don't push PRs, only build locally
          tags: theta142/mumbot:latest
      
      - name: Install Ansible on runner
        run: |
          sudo apt-get install -y ansible
      
      - name: Install necessary Python packages on runner
        run: |
          pip3 install docker
          
      - name: Set pending commit status
        uses: octokit/request-action@v2.1.0
        with:
          route: POST /repos/{owner}/{repo}/statuses/{sha}
          owner: Psyjnir
          repo: mumbot-irc
          description: "Mumbotest successful run"
          context: Mumbotest
          sha: ${{ github.sha }}
          state: pending
        env:
          GITHUB_TOKEN: ${{ secrets.GH_COMMIT_STATUS_TOKEN }}
          
      - name: Run test deployment playbook on localhost
        env:
          # Config
          GH_COMMIT_STATUS_TOKEN: ${{ secrets. GH_COMMIT_STATUS_TOKEN }}
          HUBOT_IRC_PASSWORD: ${{ secrets.HUBOT_IRC_PASSWORD }}
          HUBOT_DISCORDER_GUILD: ${{ secrets.HUBOT_DISCORDER_GUILD }}
          HUBOT_DISCORDER_TOKEN: ${{ secrets.HUBOT_DISCORDER_TOKEN }}
          HUBOT_GIPHY_API_KEY: ${{ secrets.HUBOT_GIPHY_API_KEY }}
          HUBOT_GOOGLE_CSE_ID: ${{ secrets.HUBOT_GOOGLE_CSE_ID }}
          HUBOT_GOOGLE_CSE_KEY: ${{ secrets.HUBOT_GOOGLE_CSE_KEY }}
        run: |
          ansible-galaxy install -r .ansible/requirements.yml && \
          echo "${{ secrets.KEYFILE_VAULT_PASS }}" > .ansible/vault_key && \
          ansible-playbook .ansible/deploy.yml \
           -i .ansible/inventory_test.yml \
           --extra-vars @.ansible/test_vars.yml \
           --vault-password-file .ansible/vault_key
